/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-06-06 17:18:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/crudweb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/crudweb/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1654256529726L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <html>\r\n");
      out.write("\r\n");
      out.write("        <head>\r\n");
      out.write("            <title>User Management Application</title>\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("        	<link rel=\"stylesheet\" href=\"http://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css\">\r\n");
      out.write("			<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("			<link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("			<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"http://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	-webkit-text-size-adjust: 100%;\r\n");
      out.write("	-webkit-tap-highlight-color: rgba(0, 0, 0, 0);\r\n");
      out.write("	background-color: var(- -bs-body-bg);\r\n");
      out.write("	color: var(- -bs-body-color);\r\n");
      out.write("	font-family: var(- -bs-body-font-family);\r\n");
      out.write("	font-size: var(- -bs-body-font-size);\r\n");
      out.write("	font-weight: var(- -bs-body-font-weight);\r\n");
      out.write("	line-height: var(- -bs-body-line-height);\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	text-align: var(- -bs-body-text-align);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("	font-family: 'Poppins', sans-serif;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	width: 240px;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	z-index: 100;\r\n");
      out.write("	background-color: #222E3C;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slidebar-header {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	height: 60px;\r\n");
      out.write("	padding: 0rem 1 rem;\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .sidebar-menu {\r\n");
      out.write("	padding: 1rem;\r\n");
      out.write("} */\r\n");
      out.write(".slidebar li {\r\n");
      out.write("	margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slidebar a {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slidebar a span:last-child {\r\n");
      out.write("	padding-right: 0rem 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-content {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin-left: 240px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	left: 240px;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	z-index: 100;\r\n");
      out.write("	width: calc(100% - 240px);\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	height: 60px;\r\n");
      out.write("	padding: 0rem 1rem;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: flex-end;\r\n");
      out.write("	border-bottom: 1px solid #ccc;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: centers;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons div {\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-image: url(\"image/pikachu.jpg\");\r\n");
      out.write("	background-color: #cccccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ti-comment:before {\r\n");
      out.write("	content: \"\\e644\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ti-bell:before {\r\n");
      out.write("	content: \"\\e6b8\";\r\n");
      out.write("	color: #6c757d;\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 1.5rem;\r\n");
      out.write("	line-height: 1.4;\r\n");
      out.write("	padding: 0.1rem 0.8rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.ti-comment {\r\n");
      out.write("	color: #6c757d;\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 1.5rem;\r\n");
      out.write("	line-height: 1.4;\r\n");
      out.write("	padding: 0.1rem 0.8rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-header {\r\n");
      out.write("	background: transparent;\r\n");
      out.write("	color: #ced4da;\r\n");
      out.write("	font-size: .75rem;\r\n");
      out.write("	padding: 1.5rem 1.5rem 0.375rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-item.active .sidebar-link:hover, .sidebar-item.active>.sidebar-link\r\n");
      out.write("	{\r\n");
      out.write("	background: linear-gradient(90deg, rgba(59, 125, 221, .1),\r\n");
      out.write("		rgba(59, 125, 221, .0875) 50%, transparent);\r\n");
      out.write("	border-left-color: #3b7ddd;\r\n");
      out.write("	color: #e9ecef;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".align-middle {\r\n");
      out.write("	vertical-align: middle !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-link, a.sidebar-link {\r\n");
      out.write("	background: #222e3c;\r\n");
      out.write("	border-left: 3px solid transparent;\r\n");
      out.write("	color: rgba(233, 236, 239, .5);\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	padding: 0.625rem 1.625rem;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	transition: background .1s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* header + main  */\r\n");
      out.write(".navbar-bg {\r\n");
      out.write("	background: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("	border-bottom: 0;\r\n");
      out.write("	box-shadow: 0 0 2rem 0 rgb(33 37 41/ 10%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-expand {\r\n");
      out.write("	flex-wrap: nowrap;\r\n");
      out.write("	justify-content: flex-start;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	padding: 0.875rem 1.375rem;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hamburger {\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hamburger, .hamburger:after, .hamburger:before {\r\n");
      out.write("	background: #495057;\r\n");
      out.write("	border-radius: 1px;\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	display: block;\r\n");
      out.write("	height: 3px;\r\n");
      out.write("	transition: background .1s ease-in-out, color .1s ease-in-out;\r\n");
      out.write("	width: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".align-self-center {\r\n");
      out.write("	align-self: center !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-expand .navbar-collapse {\r\n");
      out.write("	display: flex !important;\r\n");
      out.write("	flex-basis: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-flag, .nav-icon {\r\n");
      out.write("	color: #6c757d;\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 1.5rem;\r\n");
      out.write("	line-height: 1.4;\r\n");
      out.write("	padding: 0.1rem 0.8rem;\r\n");
      out.write("	transition: background .1s ease-in-out, color .1s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-toggle {\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-light .navbar-nav .nav-link {\r\n");
      out.write("	color: rgba(0, 0, 0, .55);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-expand .navbar-nav .nav-link {\r\n");
      out.write("	padding-left: 0.5rem;\r\n");
      out.write("	padding-right: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-toggle {\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li {\r\n");
      out.write("	text-align: -webkit-match-parent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav {\r\n");
      out.write("	direction: ltr;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	padding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-dark { -\r\n");
      out.write("	-bs-text-opacity: 1;\r\n");
      out.write("	color: rgba(var(- -bs-dark-rgb), var(- -bs-text-opacity)) !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("*, :after, :before {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-toggle {\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 992px) .content {\r\n");
      out.write("	padding\r\n");
      out.write("	:\r\n");
      out.write("	 \r\n");
      out.write("	3rem\r\n");
      out.write("	 \r\n");
      out.write("	3rem\r\n");
      out.write("	 \r\n");
      out.write("	1\r\n");
      out.write("	.5rem\r\n");
      out.write("	;\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) .content {\r\n");
      out.write("	max-width\r\n");
      out.write("	:\r\n");
      out.write("	 \r\n");
      out.write("	auto\r\n");
      out.write("	;\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("	width\r\n");
      out.write("	:\r\n");
      out.write("	 \r\n");
      out.write("	auto\r\n");
      out.write("	;\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("	direction: ltr;\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	max-width: 100vw;\r\n");
      out.write("	padding: 1.5rem 1.5rem 0.75rem;\r\n");
      out.write("	width: 100vw;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer.footer {\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	direction: ltr;\r\n");
      out.write("	padding: 1rem 0.875rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mb-0 {\r\n");
      out.write("	margin-bottom: 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("	margin-bottom: 1rem;\r\n");
      out.write("	margin-top: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer.footer ul {\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-inline, .list-unstyled {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	padding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("	display: block;\r\n");
      out.write("	list-style-type: disc;\r\n");
      out.write("	margin-block-start: 1em;\r\n");
      out.write("	margin-block-end: 1em;\r\n");
      out.write("	margin-inline-start: 0px;\r\n");
      out.write("	margin-inline-end: 0px;\r\n");
      out.write("	/* padding-inline-start: 40px; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-end {\r\n");
      out.write("    text-align: right !important;\r\n");
      out.write("    width: 50%;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-muted { -\r\n");
      out.write("	-bs-text-opacity: 1;\r\n");
      out.write("	color: #6c757d !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row { -\r\n");
      out.write("	-bs-gutter-x: 24px; -\r\n");
      out.write("	-bs-gutter-y: 0;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	margin-left: calc(var(- -bs-gutter-x)*-.5);\r\n");
      out.write("	margin-right: calc(var(- -bs-gutter-x)*-.5);\r\n");
      out.write("	margin-top: calc(var(- -bs-gutter-y)*-1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row { -\r\n");
      out.write("	-bs-gutter-x: 24px; -\r\n");
      out.write("	-bs-gutter-y: 0;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	margin-left: calc(var(- -bs-gutter-x)*-.5);\r\n");
      out.write("	margin-right: calc(var(- -bs-gutter-x)*-.5);\r\n");
      out.write("	margin-top: calc(var(- -bs-gutter-y)*-1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer.footer {\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	direction: ltr;\r\n");
      out.write("	padding: 1rem 0.875rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-item .indicator {\r\n");
      out.write("	background: #3b7ddd;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	box-shadow: 0 0.1rem 0.2rem rgb(0 0 0/ 5%);\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: .675rem;\r\n");
      out.write("	height: 18px;\r\n");
      out.write("	padding: 1px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: -8px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	transition: top .1s ease-out;\r\n");
      out.write("	width: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-flag, .nav-icon {\r\n");
      out.write("	color: #6c757d;\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 1.5rem;\r\n");
      out.write("	line-height: 1.4;\r\n");
      out.write("	padding: 0.1rem 0.8rem;\r\n");
      out.write("	transition: background .1s ease-in-out, color .1s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-toggle {\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	color: #3b7ddd;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav {\r\n");
      out.write("	direction: ltr;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	padding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("	border-bottom: 0;\r\n");
      out.write("	box-shadow: 0 0 2rem 0 rgb(33 37 41/ 10%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-expand {\r\n");
      out.write("	flex-wrap: nowrap;\r\n");
      out.write("	justify-content: flex-start;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("    margin-left: 131px;\r\n");
      out.write("    /* margin-top: 550px; */\r\n");
      out.write("}\r\n");
      out.write("ul.list-inline {\r\n");
      out.write("    display: block;\r\n");
      out.write("    list-style-type: disc;\r\n");
      out.write("    margin-block-start: 1em;\r\n");
      out.write("    margin-block-end: 1em;\r\n");
      out.write("    margin-inline-start: 0px;\r\n");
      out.write("    margin-inline-end: 0px;\r\n");
      out.write("    padding-inline-start: 40px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("footer.footer ul {\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write(".col-6.text-start {\r\n");
      out.write("    width: 50%;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("}\r\n");
      out.write("li.list-inline-item {\r\n");
      out.write("    float: right;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    margin-top: -30px;\r\n");
      out.write("}\r\n");
      out.write("span.text-dark {\r\n");
      out.write("    margin-left: 7px;\r\n");
      out.write("    margin-right: 14px;\r\n");
      out.write("}\r\n");
      out.write("img {\r\n");
      out.write("    width: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-list {\r\n");
      out.write("    background-color: #4950571a;\r\n");
      out.write("    padding-bottom: 300px;\r\n");
      out.write("    padding-left: 190px;\r\n");
      out.write("}\r\n");
      out.write("th {\r\n");
      out.write("    background-color: #5cb1f3;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"sidebar\" style=\"wight: 20%\">\r\n");
      out.write("		<div class=\"slidebar-header\">\r\n");
      out.write("			<h3 class=\"brand\">\r\n");
      out.write("\r\n");
      out.write("				<span>De Tai 14</span>\r\n");
      out.write("			</h3>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"sidebar-menu\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li class=\"sidebar-header\">Pages</li>\r\n");
      out.write("				<li class=\"sidebar-item active\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"{{url_for('_user.index')}}\"> <i class=\"align-middle\"\r\n");
      out.write("						data-feather=\"sliders\"></i> <span class=\"align-middle\">Dashboard</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"{{url_for('_createDatabase.index')}}\"> <i\r\n");
      out.write("						class=\"align-middle me-2\" data-feather=\"database\"></i> <span\r\n");
      out.write("						class=\"align-middle\">New Database</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"{{url_for('_createTable.index')}}\"> <i\r\n");
      out.write("						class=\"align-middle me-2\" data-feather=\"credit-card\"></i> <span\r\n");
      out.write("						class=\"align-middle\">New Table</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- <div class=\"main-content\">\r\n");
      out.write("			<header>\r\n");
      out.write("				<span class=\"image\" href=\"image/pikachu.jpg\"></span>\r\n");
      out.write("				<div class=\"social-icons\">\r\n");
      out.write("					<span class=\"ti-bell\"></span> <span class=\"ti-comment\"></span>\r\n");
      out.write("					<img src=\"goku.jpg\" class=\"avatar img-fluid rounded\" alt=\"Charles Hall\">\r\n");
      out.write("					<img style=\"width: 32px;\"\r\n");
      out.write("						src=\"https://media-cdn-v2.laodong.vn/Storage/NewsPortal/2020/6/30/816260/Cho-1.jpg\">\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</header>\r\n");
      out.write("		</div> -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"main\" style=\"wight: 80%\">\r\n");
      out.write("		<div class=\"main-content\">\r\n");
      out.write("			<header>\r\n");
      out.write("				<span class=\"image\" href=\"image/pikachu.jpg\"></span>\r\n");
      out.write("				<div class=\"social-icons\">\r\n");
      out.write("					<span class=\"ti-bell\"></span> <span class=\"ti-comment\"></span> <img\r\n");
      out.write("						style=\"width: 32px;\"\r\n");
      out.write("						src=\"https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg\">\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<span class=\"text-dark\">kimngan</span>\r\n");
      out.write("			</header>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"user-list\">\r\n");
      out.write("                <!-- <div class=\"alert alert-success\" *ngIf='message'>{{message}}</div> -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <h3 class=\"text-center\">Users</h3>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <div class=\"container text-left\">\r\n");
      out.write("\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/new\" class=\"btn btn-success\">Add Row</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <table class=\"table table-bordered\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>ID</th>\r\n");
      out.write("                                <th>Name</th>\r\n");
      out.write("                                <th>Email</th>\r\n");
      out.write("                                <th>Country</th>\r\n");
      out.write("                                <th>Actions</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <!--   for (Todo todo: todos) {  -->\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            <!-- } -->\r\n");
      out.write("                        </tbody>\r\n");
      out.write("\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("	<div class=\"footer\">\r\n");
      out.write("			<footer class=\"footer\">\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<div class=\"row text-muted\">\r\n");
      out.write("						<div class=\"col-6 text-start\">\r\n");
      out.write("							<p class=\"mb-0\">\r\n");
      out.write("								<a class=\"text-muted\" href=\"https://adminkit.io/\"\r\n");
      out.write("									target=\"_blank\"><strong>De tai 14</strong></a> &copy;\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-6 text-end\">\r\n");
      out.write("							<ul class=\"list-inline\">\r\n");
      out.write("								<li class=\"list-inline-item\"><a class=\"text-muted\"\r\n");
      out.write("									href=\"https://adminkit.io/\" target=\"_blank\">Support</a></li>\r\n");
      out.write("								<li class=\"list-inline-item\"><a class=\"text-muted\"\r\n");
      out.write("									href=\"https://adminkit.io/\" target=\"_blank\">Help Center</a></li>\r\n");
      out.write("								<li class=\"list-inline-item\"><a class=\"text-muted\"\r\n");
      out.write("									href=\"https://adminkit.io/\" target=\"_blank\">Privacy</a></li>\r\n");
      out.write("								<li class=\"list-inline-item\"><a class=\"text-muted\"\r\n");
      out.write("									href=\"https://adminkit.io/\" target=\"_blank\">Terms</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</footer>\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /user-list.jsp(574,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("user");
      // /user-list.jsp(574,28) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/user-list.jsp(574,28) '${listUser}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listUser}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("                                <tr>\r\n");
            out.write("                                    <td>\r\n");
            out.write("                                        ");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                                    </td>\r\n");
            out.write("                                    <td>\r\n");
            out.write("                                        ");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                                    </td>\r\n");
            out.write("                                    <td>\r\n");
            out.write("                                        ");
            if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                                    </td>\r\n");
            out.write("                                    <td>\r\n");
            out.write("                                        ");
            if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                                    </td>\r\n");
            out.write("                                    <td><a href=\"edit?id=");
            if (_jspx_meth_c_005fout_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\">Edit</a> &nbsp;&nbsp;&nbsp;&nbsp; <a href=\"delete?id=");
            if (_jspx_meth_c_005fout_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\">Delete</a></td>\r\n");
            out.write("                                </tr>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /user-list.jsp(578,40) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /user-list.jsp(581,40) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /user-list.jsp(584,40) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /user-list.jsp(587,40) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.country}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /user-list.jsp(589,57) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f5_reused = false;
    try {
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /user-list.jsp(589,140) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      _jspx_th_c_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f5_reused);
    }
    return false;
  }
}
